site_name: libCacheSim
site_url: https://libCacheSim.com
repo_url: https://github.com/1a1a11a/libCacheSim
repo_name: 1a1a11a/libCacheSim

nav:
  - Getting Started:
    - Overview: index.md
    - Installation: getting-started/install.md
    - Cache Simulator: getting-started/quickstart/quickstart_cachesim.md
    - MRC Profiler: getting-started/quickstart/quickstart_mrcProfiler.md
    - Trace Analyzer: getting-started/quickstart/quickstart_traceAnalyzer.md
    - Trace Utilities: getting-started/quickstart/quickstart_traceUtils.md
    - Advanced: advanced/advanced_lib.md
    - Advanced Extensions: advanced/advanced_lib_extend.md
  - API Reference:
    - Overview: api/API.md
  - Profiling:
    - Performance: profiling/performance.md
    - Memory Usage: profiling/memory_usage_profiling.md
  - Development:
    - Debugging: develop/debug.md
theme:
  name: material
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Open Sans
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - navigation.footer

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]

copyright: Copyright &copy; 2025 libCacheSim Team
