from __future__ import annotations

from ._libcachesim import (
    Cache,
    Reader,
    Request,
    ReqOp,
    TraceType,
    __doc__,
    __version__,
    open_trace,
    process_trace,
    process_trace_python_hook,
)
from .eviction import (
    ARC,
    Belady,
    BeladySize,
    Cacheus,
    Clock,
    FIFO,
    LeCaR,
    LFU,
    LFUDA,
    LRB,
    LRU,
    PythonHookCachePolicy,
    QDLP,
    S3FIFO,
    Sieve,
    SLRU,
    ThreeLCache,
    TinyLFU,
    TwoQ,
    WTinyLFU,
)
from .trace_generator import (
    create_zipf_requests,
    create_uniform_requests,
)

__all__ = [
    "ARC",
    "Belady",
    "BeladySize",
    "Cacheus",
    "Cache",
    "Clock",
    "FIFO",
    "LeCaR",
    "LFU",
    "LFUDA",
    "LRB",
    "LRU",
    "PythonHookCachePolicy",
    "QDLP",
    "Reader",
    "Request",
    "ReqOp",
    "S3FIFO",
    "Sieve",
    "SLRU",
    "ThreeLCache",
    "TinyLFU",
    "TraceType",
    "TwoQ",
    "WTinyLFU",
    "__doc__",
    "__version__",
    "open_trace",
    "process_trace",
    "process_trace_python_hook",
    # Trace generators
    "create_zipf_requests",
    "create_uniform_requests",
]
