"""
Reader protocol for libCacheSim Python bindings.

ReaderProtocol defines the interface contract for trace readers,
enabling different implementations (Python/C++) to work interchangeably.
"""

from __future__ import annotations
from typing import Protocol, runtime_checkable, TYPE_CHECKING

if TYPE_CHECKING:
    from .libcachesim_python import Request


@runtime_checkable
class ReaderProtocol(Protocol):
    """Protocol for trace readers

    This protocol ensures that different reader implementations
    (SyntheticReader, TraceReader) can be used interchangeably.
    """

    def get_num_of_req(self) -> int: ...
    def read_one_req(self, req: Request) -> Request: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def clone(self) -> "ReaderProtocol": ...
    def read_first_req(self, req: Request) -> Request: ...
    def read_last_req(self, req: Request) -> Request: ...
    def skip_n_req(self, n: int) -> int: ...
    def read_one_req_above(self, req: Request) -> Request: ...
    def go_back_one_req(self) -> None: ...
    def set_read_pos(self, pos: float) -> None: ...
    def get_read_pos(self) -> float: ...
