from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from .libcachesim_python import Request, CacheObject, Reader, Analyzer


class CacheProtocol(Protocol):
    def get(self, req: Request) -> bool: ...

    def find(self, req: Request, update_cache: bool = True) -> CacheObject: ...

    def can_insert(self, req: Request) -> bool: ...

    def insert(self, req: Request) -> CacheObject: ...

    def need_eviction(self, req: Request) -> bool: ...

    def evict(self, req: Request) -> CacheObject: ...

    def remove(self, obj_id: int) -> bool: ...

    def to_evict(self, req: Request) -> CacheObject: ...

    def get_occupied_byte(self) -> int: ...

    def get_n_obj(self) -> int: ...

    def print_cache(self) -> str: ...

    def process_trace(self, reader: "ReaderProtocol", start_req: int = 0, max_req: int = -1) -> tuple[float, float]: ...

    # Properties
    @property
    def cache_size(self) -> int: ...

    @property
    def cache_name(self) -> str: ...


class ReaderProtocol(Protocol):
    def get_num_of_req(self) -> int: ...

    def read_one_req(self, req: Request) -> Request: ...

    def reset(self) -> None: ...

    def close(self) -> None: ...

    def clone(self) -> ReaderProtocol: ...

    def read_first_req(self, req: Request) -> Request: ...

    def read_last_req(self, req: Request) -> Request: ...

    def skip_n_req(self, n: int) -> int: ...

    def read_one_req_above(self, req: Request) -> Request: ...

    def go_back_one_req(self) -> None: ...

    def set_read_pos(self, pos: float) -> None: ...

    def get_read_pos(self) -> float: ...


class AnalyzerProtocol(Protocol):
    def run(self) -> None: ...

    def cleanup(self) -> None: ...
