//! Generated FFI bindings for libCacheSim
//!
//! This module contains the raw, unsafe bindings generated by bindgen.
//! These bindings should not be used directly - use the safe wrappers in the parent crate instead.

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Note: cache_t, reader_t, and request_t are already defined as type aliases in the generated bindings

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem;

    #[test]
    fn test_basic_types_exist() {
        // Ensure basic types are properly generated
        assert!(mem::size_of::<cache_t>() > 0);
        assert!(mem::size_of::<reader_t>() > 0);
        assert!(mem::size_of::<request_t>() > 0);
        assert!(mem::size_of::<common_cache_params_t>() > 0);
        assert!(mem::size_of::<reader_init_param_t>() > 0);
        assert!(mem::size_of::<obj_id_t>() == 8); // Should be u64
    }

    #[test]
    fn test_enums_exist() {
        // Test that enums are properly generated
        let _trace_type = trace_type_e::CSV_TRACE;
        let _req_op = req_op_e::OP_GET;
        let _trace_format = trace_format_e::BINARY_TRACE_FORMAT;
    }

    #[test]
    fn test_request_structure() {
        // Test that we can create and manipulate request structures
        let mut req = unsafe { std::mem::zeroed::<request_t>() };
        req.obj_id = 12345;
        req.obj_size = 1024;
        req.op = req_op_e::OP_GET;
        req.valid = true;

        assert_eq!(req.obj_id, 12345);
        assert_eq!(req.obj_size, 1024);
        assert_eq!(req.op, req_op_e::OP_GET);
        assert!(req.valid);
    }

    #[test]
    fn test_cache_params_structure() {
        // Test that we can create cache parameters
        let params = common_cache_params_t {
            cache_size: 1024 * 1024,
            default_ttl: 3600,
            hashpower: 20,
            consider_obj_metadata: false,
        };

        assert_eq!(params.cache_size, 1024 * 1024);
        assert_eq!(params.default_ttl, 3600);
        assert_eq!(params.hashpower, 20);
        assert!(!params.consider_obj_metadata);
    }

    #[test]
    fn test_reader_params_structure() {
        // Test that we can create reader parameters
        let mut params = reader_init_param_t {
            ignore_obj_size: false,
            ignore_size_zero_req: true,
            obj_id_is_num: true,
            obj_id_is_num_set: false,
            cap_at_n_req: -1,
            time_field: 0,
            obj_id_field: 0,
            obj_size_field: 0,
            op_field: 0,
            ttl_field: 0,
            cnt_field: 0,
            tenant_field: 0,
            next_access_vtime_field: 0,
            n_feature_fields: 0,
            feature_fields: [0; 16],
            block_size: -1,
            has_header: false,
            has_header_set: false,
            delimiter: b',' as i8,
            trace_start_offset: 0,
            binary_fmt_str: std::ptr::null_mut(),
            sampler: std::ptr::null_mut(),
        };

        assert!(!params.ignore_obj_size);
        assert!(params.ignore_size_zero_req);
        assert!(params.obj_id_is_num);
        assert_eq!(params.delimiter, b',' as i8);
    }
}
