use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    // Specify the header file
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let header = PathBuf::from(&manifest_dir)
        .join("..")
        .join("libCacheSim/include/libCacheSim.h");
    let lib_path = PathBuf::from(&manifest_dir)
        .join("..")
        .join("libCacheSim/_build/liblibCacheSim.a");
    // This is the path to the object file generated by bindgen for inline functions.
    let binding_dir = PathBuf::from(&manifest_dir).join("bindings");
    let rust_src_dir = PathBuf::from(&manifest_dir)
        .join("src");
    let obj_path = binding_dir.join("wrap_static_fns.o");
    let source_path = binding_dir.join("wrap_static_fns.c");
    let lib_obj_path = binding_dir.join("libwrap_static_fns.a");

    // Get GLib include paths using pkg-config
    let glib_cflags = Command::new("pkg-config")
        .args(&["--cflags", "glib-2.0"])
        .output()
        .expect("Failed to run pkg-config")
        .stdout;

    let glib_cflags = String::from_utf8_lossy(&glib_cflags);
    let include_paths: Vec<&str> = glib_cflags
        .split_whitespace()
        .filter(|s| s.starts_with("-I"))
        .map(|s| s.trim_start_matches("-I"))
        .take(2)
        .collect();
    println!("GLib include paths: {:?}", include_paths);

    // Generate bindings
    // let bindings = bindgen::Builder::default()
    //     .header(header.to_str().unwrap())
    //     .clang_arg("-xc++") // Treat the header as C++
    //     .clang_arg("-std=c++14") // Specify the C++ standard
    //     // Add GLib include paths
    //     .clang_arg(format!("-I{}", include_paths[0]))// Add GLib include paths
    //     .clang_arg(format!("-I{}", include_paths[1]))
    //     // Block problematic templates
    //     .blocklist_item("_Tp") // Skip unknown template types
    //     .blocklist_item("std::.*") // Skip all std:: types (optional)
    //     // Bindgen output options
    //     .wrap_static_fns(true)
    //     // .generate_inline_functions(true) // supports inline C++ functions too
    //     .disable_name_namespacing() // keeps names simple
    //     .layout_tests(false) // faster compilation, skips layout tests
    //     .generate()
    //     .expect("Unable to generate bindings");

    // // // Generate bindings
    // let bindings = bindgen::Builder::default()
    //     .header(header.to_str().unwrap())
    //     .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
    //     .clang_arg("-xc++")
    //     .clang_arg("-std=c++14") // Specify the C++ standard
    //     .clang_arg(format!("-I{}", include_paths[0]))// Add GLib include paths
    //     .clang_arg(format!("-I{}", include_paths[1]))
    //     // .clang_arg(format!("-I{}", "/opt/homebrew/Cellar/zstd/1.5.7"))
    //     .blocklist_item("_Tp") // Skip unknown template types
    //     .blocklist_item("std::.*") // Skip all std:: types (optional)
    //     // .blocklist_file(".*/glib-2.0/.*")
    //     // .blocklist_file(".*/CommandLineTools/.*")
    //     // .blocklist_file(".*zstdReader.*")
    //     // .wrap_static_fns(true)
    //     // .wrap_static_fns_suffix("__extern")
    //     // .wrap_static_fns_path(rust_src_dir.join("wrap_static_fns.c"))// Bindgen output options
    //     .disable_name_namespacing()
    //     .layout_tests(false)
    //     .use_core() // Use core types
    //     .ctypes_prefix("libc") // Explicitly link to libc types like FILE
    //     // .clang_args(&["-x", "c++", "-std=c++14", &format!("-I{}", include_paths[0]), &format!("-I{}", include_paths[1]), &format!("-I{}", "/opt/homebrew/Cellar/zstd/1.5.7")])
    //     .generate()
    //     .expect("Unable to generate bindings");

    
    // wrap_static_fns does not generate wrap_static_fns.c when xc++ flag is on, see issue 
    // on bindgen https://github.com/rust-lang/rust-bindgen/issues/3157
    // Now, what we do is that:
    //  1) we comment out .clang_arg(&["-x", "c++", "-std=c++14"]) and .blocklist_file(".*/glib-2.0/((?!include/glibconfig\\.h).)*$")

    // Generate bindings
    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .blocklist_file(".*/glib-2.0/glib/.*")
        // .blocklist_file(".*/CommandLineTools/.*")
        .blocklist_file(".*zstdReader.*")
        .blocklist_item("_Tp") // Skip unknown template types
        .blocklist_item("std::.*") // Skip all std:: types (optional)
        .wrap_static_fns(true)
        .wrap_static_fns_suffix("__extern")
        .wrap_static_fns_path(binding_dir.join("wrap_static_fns.c"))// Bindgen output options
        .clang_args(&[
                    // "-x",
                    // "c++",
                    // "-std=c++14",
                    &format!("-I{}", include_paths[0]), 
                    &format!("-I{}", include_paths[1]), 
                    &format!("-I{}", "/opt/homebrew/Cellar/zstd/1.5.7")
        ])
        .generate()
        .expect("Unable to generate bindings");

    
    // Compile the generated wrappers into an object file.
    let clang_output = std::process::Command::new("clang")
        .arg("-O")
        .arg("-c")
        .arg("-o")
        .arg(&obj_path)
        .arg(source_path)
        .arg("-include")
        .arg(header)
        .arg(format!("-I{}", include_paths[0]))
        .arg(format!("-I{}", include_paths[1]))
        .arg(format!("-I{}", "/opt/homebrew/Cellar/zstd/1.5.7"))
        .output()
        .unwrap();

    if !clang_output.status.success() {
        panic!(
            "Could not compile object file:\n{}",
            String::from_utf8_lossy(&clang_output.stderr)
        );
    }

    // Turn the object file into a static library
    let lib_output = Command::new("ar")
        .arg("rcs")
        .arg(lib_obj_path)
        .arg(obj_path)
        .output()
        .unwrap();
    if !lib_output.status.success() {
        panic!(
            "Could not emit library file:\n{}",
            String::from_utf8_lossy(&lib_output.stderr)
        );
    }

    // Tell cargo to statically link against the `libwrap_static_fns` static library.
    println!("cargo:rustc-link-search={}", binding_dir.to_str().unwrap());
    println!("cargo:rustc-link-lib=static=wrap_static_fns");

    println!("cargo:rustc-link-search=../_build");
    println!("cargo:rustc-link-lib=static=libCacheSim");

    // Link ZSTD and GLib dynamically
    println!("cargo:rustc-link-lib=zstd");
    // Add GLib and Gettext library paths
    println!("cargo:rustc-link-search=native=/opt/homebrew/Cellar/glib/2.84.0/lib");
    println!("cargo:rustc-link-search=native=/opt/homebrew/opt/gettext/lib");
    // Link GLib and intl from Gettext
    println!("cargo:rustc-link-lib=glib-2.0");
    println!("cargo:rustc-link-lib=intl");

    println!("cargo:rustc-link-arg=-mmacosx-version-min=15.1");

    // Write the bindings to the $libcachesim-rs/src/bindings.rs file
    bindings
        .write_to_file(binding_dir.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}


// use std::env;
// use std::path::PathBuf;

// fn main() {
//     // Link to the C++ standard library
//     // println!("cargo:rustc-link-search=/opt/homebrew/opt/gcc/lib/gcc/current");
//     println!("cargo:rustc-link-arg=-mmacosx-version-min=15.1");
//     println!("cargo:rustc-link-lib=zstd");
//     println!("cargo:rustc-link-lib=glib-2.0");
//     println!("cargo:rustc-link-lib=c++");

//     println!("cargo:rustc-link-search=../_build");
//     println!("cargo:rustc-link-lib=static=libCacheSim");

//     println!("cargo:rustc-link-search=/Users/yangliu/Desktop/Research/libCacheSim/libcachesim-rs/src");
//     println!("cargo:rustc-link-lib=static=wrap_static_fns");


//     // Specify the header file
//     let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
//     let header = PathBuf::from(&manifest_dir)
//         .join("..")
//         .join("libCacheSim/include/libCacheSim.h");

//     // Get GLib include paths
//     let glib_include_path = "/opt/homebrew/Cellar/glib/2.84.0/include/glib-2.0";
//     let glib_config_include = "/opt/homebrew/Cellar/glib/2.84.0/lib/glib-2.0/include";


//     // Generate bindings
//     let bindings = bindgen::Builder::default()
//         .header(header.to_str().unwrap())
//         .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
//         // Bindgen output options
//         .wrap_static_fns_path("/Users/yangliu/Desktop/Research/libCacheSim/libcachesim-rs/src/wrap_static_fns")
//         .wrap_static_fns(true)
//         .clang_arg("-xc++") // Treat the header as C++
//         .clang_arg("-std=c++14") // Specify the C++ standard
//         // Add GLib include paths
//         .clang_arg(format!("-I{}", glib_include_path))
//         .clang_arg(format!("-I{}", glib_config_include))
//         // Block problematic templates
//         .blocklist_item("_Tp") // Skip unknown template types
//         .blocklist_item("std::.*") // Skip all std:: types (optional)
//         .blocklist_item(".*zstdReader.*")
//         // .generate_inline_functions(true) // supports inline C++ functions too
//         // .disable_name_namespacing() // keeps names simple
//         .generate()
//         .expect("Unable to generate bindings");

//     // This is the path to the object file.
//     let obj_path = "/Users/yangliu/Desktop/Research/libCacheSim/libcachesim-rs/src/libwrap_static_fns.o";
//     // This is the path to the static library file.
//     let lib_path = "/Users/yangliu/Desktop/Research/libCacheSim/_build/liblibCacheSim.a";

//     // Compile the generated wrappers into an object file.
//     let clang_output = std::process::Command::new("clang")
//         .arg("-O")
//         .arg("-c")
//         .arg("-o")
//         .arg(&obj_path)
//         .arg(std::env::temp_dir().unwrap().join("bindgen").join("/Users/yangliu/Desktop/Research/libCacheSim/libcachesim-rs/src/libwrap_static_fns.c"))
//         .arg("-include")
//         .arg(input)
//         .output()
//         .unwrap();

//     // Write the bindings to the $libcachesim-rs/src/bindings.rs file
//     let bindings_path = PathBuf::from(&manifest_dir)
//         .join("src")
//         .join("bindings.rs");
//     bindings
//         .write_to_file(bindings_path)
//         .expect("Couldn't write bindings!");
// }

