//
// Created by Juncheng Yang on 4/11/21.
//

#ifndef LIBCACHESIM_LIBCACHESIM_EVICTIONALGO_SEGCACHE_H_
#define LIBCACHESIM_LIBCACHESIM_EVICTIONALGO_SEGCACHE_H_

#endif //LIBCACHESIM_LIBCACHESIM_EVICTIONALGO_SEGCACHE_H_
